#!/usr/bin/python

"""Amulet tests on a basic keystone deployment on utopic-juno."""

from basic_deployment import KeystoneBasicDeployment

if __name__ == '__main__':
    deployment = KeystoneBasicDeployment(series='utopic')
    deployment.run_tests()
