#!/usr/bin/python

"""Amulet tests on a basic keystone deployment on precise-essex."""

from basic_deployment import KeystoneBasicDeployment

if __name__ == '__main__':
    deployment = KeystoneBasicDeployment(series='precise')
    deployment.run_tests()
