#!/usr/bin/python

"""Amulet tests on a basic keystone deployment on precise-folsom."""

from basic_deployment import KeystoneBasicDeployment

if __name__ == '__main__':
    deployment = KeystoneBasicDeployment(series='precise',
                                         openstack='cloud:precise-folsom',
                                         source='cloud:precise-updates/folsom')
    deployment.run_tests()
