#!/usr/bin/python

"""Amulet tests on a basic keystone deployment on precise-grizzly."""

from basic_deployment import KeystoneBasicDeployment

if __name__ == '__main__':
    deployment = KeystoneBasicDeployment(series='precise',
                                         openstack='cloud:precise-grizzly',
                                         source='cloud:precise-updates/grizzly')
    deployment.run_tests()
