#!/usr/bin/python

"""Amulet tests on a basic keystone deployment on precise-havana."""

from basic_deployment import KeystoneBasicDeployment

if __name__ == '__main__':
    deployment = KeystoneBasicDeployment(series='precise',
                                         openstack='cloud:precise-havana')
    deployment.run_tests()
