#!/usr/bin/python
import sys
sys.path.append('hooks/')

from charmhelpers.contrib.openstack.utils import (
    git_install_requested,
)

from charmhelpers.core.hookenv import (
    action_set,
    action_fail,
    config,
)

from keystone_utils import (
    git_install,
)


def git_reinstall():
    """Reinstall from source and restart services.

    If the openstack-origin-git config option was used to install openstack
    from source git repositories, then this action can be used to reinstall
    from updated git repositories, followed by a restart of services."""
    if not git_install_requested():
        action_fail("openstack-origin-git is not configured")

    git_install(config('openstack-origin-git'))

    action_set({'status': "git-reinstall action completed"})


if __name__ == '__main__':
    git_reinstall()
