#!/usr/bin/python

import sys

from charmhelpers.core import hookenv, host

from hooks.keystone_utils import determine_services


if __name__ == "__main__":
    for service in determine_services():
        if not host.service_resume(service):
            hookenv.action_fail("Failed to resume service {}.".format(service))
            sys.exit(-1)
